<?php

namespace modules\billmanagervps\classes\model;

use System\ObjectModel;

class Plan extends ObjectModel {
    protected static $table = 'billmanagervps_plans';

    public function remove()
    {
        $orderObject = new Order();
        $orderObject->where('plan_id', $this->id)->removeRows();

        return parent::remove(); // TODO: Change the autogenerated stub
    }
}